apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1
vpc:
  id: vpc-0c1644902d274d775  # Use your existing VPC ID
  subnets:
    public:
      us-east-1a:
        id: subnet-0326e9a1e993ebef7  # Specify public subnet ID
      us-east-1b:
        id: subnet-07ec2ffbc1580d0c9  # Specify public subnet ID
managedNodeGroups:
- name: expense
  instanceType: t3.medium
  desiredCapacity: 3
  Spot: true